name: Docker CI with Github Actions

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build & push multi-arch Docker image
              uses: docker/build-push-action@v6
              with:
                  platforms: linux/amd64,linux/arm64
                  push: true
                  image: jeanarmel/user-service-api
                  tags: 1.0, latest
                  registry: docker.io
                  dockerfile: Dockerfile
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
