name: Docker CI with Github Actions

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build & push Docker image
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                  image: jeanarmel/user-service-api
                  tags: v1.0, latest
                  registry: docker.io
                  dockerfile: Dockerfile
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
